# Generated by Django 4.2.7 on 2023-12-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
